input_files:
  metadata: ".2025-11-11/metadata.tsv"
  reference_fasta: ".2025-11-11/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta"
  haplotype_database_file: ".2025-11-11/Homo_sapiens_assembly38.haplotype_database.txt"
  # MUST INCLUDE INDEX FILES WITH BELOW (same names just with .tbi extension)
  # # known_indel_sites_vcfs must be a list (can't be just one vcf i.e. string)
  known_indel_sites_vcfs: [".2025-11-11/Homo_sapiens_assembly38.known_indels.vcf.gz", ".2025-11-11/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"]
  dbsnp_vcf: ".2025-11-11/Homo_sapiens_assembly38.dbsnp138.vcf"
  wgs_coverage_interval_list: ".2025-11-11/wgs_coverage_regions.hg38.interval_list"
  calling_interval_list: ".2025-11-11/wgs_evaluation_regions.hg38.interval_list"
  split_interval_list: ".2025-11-11/wgs_calling_regions.hg38.noCentromeres.noTelomeres.interval_list"
  evaluation_interval_list: ".2025-11-11/wgs_evaluation_regions.hg38.interval_list"
  str_table_file: ".2025-11-11/GRCh38_no_alt_analysis_set_GCA_000001405.15.str_table.tsv"

platform: "Illumina"
compression_level: 2
unmap_contaminant_reads: True
lod_threshold: -20.0
cross_check_fingerprints_by: "READGROUP"
picard_tmp_dir: ".picard" # CANNOT BE UNDER /tmp
contamination_sites:
  ud: ".2025-11-11/1000g.phase3.100k.b38.vcf.gz.dat.UD"
  bed: ".2025-11-11/1000g.phase3.100k.b38.vcf.gz.dat.bed"
  mu: ".2025-11-11/1000g.phase3.100k.b38.vcf.gz.dat.mu"
contamination_underestimation_factor: 0.75
bin_base_qualities: true
somatic: false
read_length: 250
scatter_interval_list:
  scatter_count: 10
  break_bands_at_multiples_of: 100000
split_interval_list:
  scatter_count_factor: 0.15
  scatter_mode: "BALANCING_WITHOUT_INTERVAL_SUBDIVISION_WITH_OVERFLOW"
import_gvcf:
  batch_size: 50

work_dir: "/zata/zippy/ramirezc/whole-genome-germline-singlesample-smk"
results_dir: "results"
tmp_dir: "/tmp"
log_dir: "logs"

environments:
  default: "docker://clarity001/wgs-smk:latest"
  gatk: "docker://us.gcr.io/broad-gatk/gatk:latest"
  picard: "docker://broadinstitute/picard:latest"
